/**
 * @fileOverview Base de données initiale pour la FAQ.
 * Déportée ici pour éviter de surcharger les composants clients.
 */

export const INITIAL_FAQ_DATA = [
  // --- GENERAL (15) ---
  { categorie: "General", ordre: 1, question: "L'application remplace-t-elle les sources officielles ?", reponse: "Non. Pour votre sécurité, consultez toujours meteo.nc et les autorités maritimes (COSS). L'app est un assistant tactique." },
  { categorie: "General", ordre: 2, question: "Pourquoi la géolocalisation est-elle indispensable ?", reponse: "Elle permet de calculer les marées de la station la plus proche de VOUS, d'activer le Boat Tracker et de vous donner les risques de gratte locaux." },
  { categorie: "General", ordre: 3, question: "Comment fonctionne le mode hors-ligne ?", reponse: "Les données consultées avec internet sont mises en cache (PWA). Le GPS fonctionne sans réseau, mais pas les mises à jour live." },
  { categorie: "General", ordre: 4, question: "L'application consomme-t-elle beaucoup de batterie ?", reponse: "Le GPS en continu (Boat Tracker) est énergivore. Utilisez le 'Mode Éveil' uniquement quand nécessaire et prévoyez une batterie externe." },
  { categorie: "General", ordre: 5, question: "Quelle est la précision des marées ?", reponse: "Nous utilisons les constantes du SHOM ajustées par algorithme selon votre commune. La précision est de +/- 10 min." },
  { categorie: "General", ordre: 6, question: "Puis-je changer ma commune favorite ?", reponse: "Oui, via le sélecteur en haut de l'écran. Votre choix est mémorisé sur votre profil." },
  { categorie: "General", ordre: 7, question: "L'application est-elle gratuite ?", reponse: "Il existe un mode 'Limité' gratuit (1 min/jour) et un mode 'Premium' illimité par abonnement." },
  { categorie: "General", ordre: 8, question: "Comment installer l'app sur mon iPhone ?", reponse: "Ouvrez Safari, appuyez sur 'Partager' puis 'Sur l'écran d'accueil'. C'est une PWA." },
  { categorie: "General", ordre: 9, question: "Comment installer l'app sur Android ?", reponse: "Via Chrome, appuyez sur les 3 points puis 'Installer l'application'." },
  { categorie: "General", ordre: 10, question: "Mes données GPS sont-elles privées ?", reponse: "Oui. Elles ne sont partagées QUE si vous activez volontairement le Boat Tracker ou une session de Chasse." },
  { categorie: "General", ordre: 11, question: "L'app fonctionne-t-elle aux Îles Loyauté ?", reponse: "Oui, les stations de Lifou, Maré et Ouvéa sont intégrées." },
  { categorie: "General", ordre: 12, question: "Qui a développé cette application ?", reponse: "Une équipe de passionnés du terroir calédonien, pour les gens du pays." },
  { categorie: "General", ordre: 13, question: "Comment signaler un bug ?", reponse: "Via l'onglet 'FAQ & Support', ouvrez un ticket technique." },
  { categorie: "General", ordre: 14, question: "L'heure affichée est-elle celle de NC ?", reponse: "Oui, l'application est configurée sur le fuseau GMT+11 (Nouméa)." },
  { categorie: "General", ordre: 15, question: "Peut-on utiliser l'app sur tablette ?", reponse: "Oui, l'interface est responsive et s'adapte aux grands écrans." },

  // --- PRO (15) ---
  { categorie: "PRO", ordre: 120, question: "Comment activer mon compte commerçant ?", reponse: "Vous devez d'abord créer un compte classique, puis transmettre votre UID (visible dans l'onglet Profil) à l'administrateur pour qu'il relie votre boutique." },
  { categorie: "PRO", ordre: 121, question: "À quoi sert l'Assistant Magicien IA Produit ?", reponse: "Il utilise la vision artificielle pour analyser vos photos de produits. En un clic, il rédige une description attractive et génère une stratégie de vente (arguments clés et conseils marketing)." },
  { categorie: "PRO", ordre: 122, question: "Comment fonctionne le Magicien de Campagne ?", reponse: "Une fois vos articles sélectionnés, l'IA rédige automatiquement 5 variantes de messages par canal (Email, SMS, Push). Elle adapte la longueur selon le format technique de chaque support." },
  { categorie: "PRO", ordre: 123, question: "Pourquoi y a-t-il 3 choix de longueur dans les campagnes ?", reponse: "Vous pouvez choisir entre Court, Moyen ou Long. L'IA adapte alors le contenu : un mail 'Court' sera plus riche qu'un SMS 'Court' pour respecter les usages de chaque média." },
  { categorie: "PRO", ordre: 124, question: "Comment est calculé le devis d'une campagne ?", reponse: "Le prix total = Frais fixes + (Nombre d'abonnés ciblés x Tarif par canal). Le 'Reach' affiche l'audience réelle atteignable selon vos rayons et votre zone géographique." },
  { categorie: "PRO", ordre: 125, question: "Comment marquer un article en rupture de stock ?", reponse: "Activez l'interrupteur 'Stock vide' dans la fiche du produit. Sélectionnez ensuite le mois et l'année du prochain arrivage prévu pour informer vos clients." },
  { categorie: "PRO", ordre: 126, question: "Qu'est-ce que l'affichage 'Rupture' côté client ?", reponse: "L'annonce apparaît en opacité réduite avec un badge rouge 'STOCK ÉPUISÉ'. Un message en gras indique la date de la prochaine commande prévue." },
  { categorie: "PRO", ordre: 127, question: "L'IA peut-elle inventer des produits dans mes messages ?", reponse: "Non. Nous avons configuré l'IA pour qu'elle respecte strictement votre catalogue. Elle n'ajoutera jamais d'articles (ex: vêtements) qui ne sont pas dans votre sélection actuelle." },
  { categorie: "PRO", ordre: 128, question: "Puis-je modifier les textes de l'IA ?", reponse: "Oui, l'étape finale du Magicien de Campagne vous permet d'éditer manuellement chaque message avant de procéder au paiement." },
  { categorie: "PRO", ordre: 129, question: "Le ciblage par commune est-il précis ?", reponse: "Oui, vous pouvez choisir jusqu'à 30 communes spécifiques. Seuls les utilisateurs ayant ces communes en 'Favori' recevront l'alerte." },
  { categorie: "PRO", ordre: 130, question: "Peut-on mettre plusieurs photos par produit ?", reponse: "Oui, vous pouvez charger jusqu'à 4 photos. L'IA les analysera toutes pour créer la meilleure description possible." },
  { categorie: "PRO", ordre: 131, question: "Pourquoi utiliser les Nouvel Arrivage sans promo ?", reponse: "Cela permet de créer de l'exclusivité et du passage en magasin sans devaluer vos marges. L'IA utilisera alors un ton centré sur la nouveauté et non sur le prix." },
  { categorie: "PRO", ordre: 132, question: "Comment savoir si ma campagne est envoyée ?", reponse: "Après le paiement, votre campagne passe en statut 'En attente'. L'administrateur valide techniquement l'envoi sous 24h et vous recevez une notification." },
  { categorie: "PRO", ordre: 133, question: "Les clients peuvent-ils me contacter ?", reponse: "Oui, via le bouton 'Contacter le magasin' sur chaque annonce. Ils peuvent vous appeler directement ou lancer un itinéraire GPS vers votre boutique." },
  { categorie: "PRO", ordre: 134, question: "Comment mettre à jour mon point GPS Boutique ?", reponse: "Allez dans l'onglet 'Profil' et cliquez sur 'Modifier mes coordonnées'. Vous pouvez alors déplacer le curseur sur la carte satellite." },

  // --- PECHE & FISH (25) ---
  { categorie: "Peche", ordre: 16, question: "Qu'est-ce qu'un indice de réussite 10/10 ?", reponse: "C'est une coïncidence parfaite entre vive-eau, phase lunaire optimale et créneau d'activité de l'espèce." },
  { categorie: "Peche", ordre: 17, question: "Comment fonctionne l'IA 'Jour Similaire' ?", reponse: "Elle compare la marée et la lune d'un succès passé pour trouver une date identique dans le futur." },
  { categorie: "Peche", ordre: 18, question: "Le scanner de poisson identifie-t-il le risque de gratte ?", reponse: "Oui, il identifie l'espèce et affiche instantanément le profil de risque différencié par taille (Petit, Moyen, Grand)." },
  { categorie: "Peche", ordre: 19, question: "Comment éviter la gratte (ciguatera) ?", reponse: "L'app vous donne un score pondéré. Évitez les spécimens de catégorie 'Grand' dans les zones à risque et consultez toujours le lien vers le guide de la CPS présent sur chaque fiche." },
  { categorie: "Peche", ordre: 20, question: "Pourquoi le risque de gratte varie-t-ils selon la taille ?", reponse: "Les toxines s'accumulent tout au long de la vie du poisson. Un grand spécimen est statistiquement beaucoup plus dangereux qu'un petit." },
  { categorie: "Peche", ordre: 21, question: "C'est quoi le 'Risque local' (Communautaire) ?", reponse: "C'est la moyenne des signalements effectués par les pêcheurs de votre commune. Elle reflète la réalité du terrain." },
  { categorie: "Peche", ordre: 22, question: "Comment est calculé le Score Final de risque ?", reponse: "C'est la moyenne exacte entre les données scientifiques (Admin) et la moyenne des signalements citoyens de la commune." },
  { categorie: "Peche", ordre: 23, question: "Que signifient les longueurs en CM sur les fiches ?", reponse: "Ce sont des repères pour vous aider à classer votre prise (ex: < 30cm = Petit) afin de consulter le bon taux de risque." },
  { categorie: "Peche", ordre: 24, question: "Comment contribuer à l'indice de risque ?", reponse: "Cliquez sur 'Ajuster le % de gratte', choisissez la taille du poisson et indiquez votre ressenti ou constatation. Votre vote met à jour la commune." },
  { categorie: "Peche", ordre: 25, question: "Quelle lune pour le crabe de palétuvier ?", reponse: "Le crabe est 'plein' autour de la nouvelle et pleine lune (vives-eaux)." },
  { categorie: "Peche", ordre: 26, question: "Pourquoi mon spot a disparu ?", reponse: "Vérifiez que vous êtes connecté au même compte. Les spots sont liés à votre email." },
  { categorie: "Peche", ordre: 27, question: "Comment utiliser l'IA 'Quel spot maintenant ?' ?", reponse: "L'IA analyse vos spots enregistrés et choisit le meilleur selon votre position GPS et la marée actuelle." },
  { categorie: "Peche", ordre: 28, question: "Mon signalement de gratte est-il anonyme ?", reponse: "Oui, il est utilisé uniquement pour mettre à jour les statistiques de sécurité collectives de la commune." },
  { categorie: "Peche", ordre: 29, question: "Comment pêcher à la traîne ?", reponse: "Visez les cassants et les passes entre 6 et 9 nœuds pour le Tazard ou le Wahoo." },
  { categorie: "Peche", ordre: 30, question: "C'est quoi le 'Similar Day Finder' ?", reponse: "C'est notre outil IA exclusif qui prédit vos chances de succès basées sur l'historique lunaire." },
  { categorie: "Peche", ordre: 31, question: "Peut-on supprimer un spot ?", reponse: "Oui, cliquez sur l'icône poubelle dans votre carnet de spots." },
  { categorie: "Peche", ordre: 32, question: "Pourquoi les indices de confiance changent-ils de couleur ?", reponse: "Vert (Faible risque), Orange (Modéré), Rouge (Élevé). C'est basé sur le score final pondéré." },
  { categorie: "Peche", ordre: 33, question: "L'app gère-t-elle les records de prises ?", reponse: "Vous pouvez noter vos records dans les 'Notes' de chaque spot." },
  { categorie: "Peche", ordre: 34, question: "Pourquoi la météo marine est payante sur d'autres sites ?", reponse: "Nous incluons une estimation de houle et vent gratuitement pour nos abonnés Premium." },
  { categorie: "Peche", ordre: 35, question: "Comment lire la flèche du vent ?", reponse: "La pointe indique où va le vent. Une flèche vers le bas signifie un vent de Nord." },
  { categorie: "Peche", ordre: 36, question: "Qu'est-ce que l'étale de marée ?", reponse: "Le moment où l'eau ne monte ni ne descend. Souvent un moment calme pour la pêche." },
  { categorie: "Peche", ordre: 37, question: "Comment pêcher la loche truite ?", reponse: "Au jig ou leurre souple près des patates de corail, entre 10 et 25m." },
  { categorie: "Peche", ordre: 38, question: "Où pêcher à Nouméa ?", reponse: "Le lagon sud regorge de spots, utilisez la carte satellite pour repérer les fonds clairs." },
  { categorie: "Peche", ordre: 39, question: "L'IA connaît-elle tous les poissons ?", reponse: "Elle connaît les espèces les plus communes du lagon calédonien. Vous pouvez en rajouter via l'admin." },
  { categorie: "Peche", ordre: 40, question: "Le vent d'Est est-il bon pour la pêche ?", reponse: "En NC, l'Alizé d'Est est le vent dominant. Il est régulier mais peut lever de la mer." },
  { categorie: "Peche", ordre: 104, question: "Comment partager un coin de pêche avec un ami ?", reponse: "Dans votre carnet de pêche, ouvrez les détails du spot et cliquez sur l'icône 'Partager' (avion en papier). Saisissez l'e-mail de votre ami et validez l'envoi." },
  { categorie: "Peche", ordre: 105, question: "L'importation d'un spot partagé est-elle automatique ?", reponse: "Oui. Dès que le destinataire ouvre son carnet de pêche, une notification s'affiche et le spot est automatiquement ajouté à sa liste personnelle." },
  { categorie: "Peche", ordre: 106, question: "Pourquoi mon ami ne reçoit-il pas mon spot ?", reponse: "Le destinataire doit posséder un compte sur l'application enregistré avec l'e-mail exact que vous avez saisi lors du partage." },

  // --- BOAT TRACKER (25) ---
  { categorie: "Boat Tracker", ordre: 41, question: "Comment mon contact me suit-il ?", reponse: "Il doit entrer votre ID unique dans son onglet 'Récepteur (B)'." },
  { categorie: "Boat Tracker", ordre: 42, question: "À quoi servent les 30 secondes au lancement ?", reponse: "C'est une phase de qualification. L'IA analyse la stabilité de votre GPS pour décider si vous êtes déjà au mouillage ou si vous faites route." },
  { categorie: "Boat Tracker", ordre: 43, question: "Que signifie 'Signal perdu' ?", reponse: "L'émetteur n'a plus de réseau ou son téléphone est éteint depuis plus de 10 min." },
  { categorie: "Boat Tracker", ordre: 44, question: "Puis-je suivre plusieurs bateaux ?", reponse: "Oui, ajoutez autant d'IDs que vous voulez dans votre flotte privée (B)." },
  { categorie: "Boat Tracker", ordre: 45, question: "Le mode éveil est-il risqué ?", reponse: "Il empêche l'écran de s'éteindre pour ne pas couper le GPS. Attention à la batterie." },
  { categorie: "Boat Tracker", ordre: 46, question: "Comment fonctionne le rayon de mouillage ajustable ?", reponse: "Vous pouvez régler le cercle bleu de 10m à 100m. Si le bateau sort physiquement de ce cercle, il repasse instantanément en statut 'En mouvement'." },
  { categorie: "Boat Tracker", ordre: 47, question: "Comment fonctionne le bouton 'Demande Assistance' ?", reponse: "Il fait passer votre navire en rouge clignotant sur la carte de vos récepteurs et déclenche une alerte sonore prioritaire chez eux." },
  { categorie: "Boat Tracker", ordre: 48, question: "C'est quoi le mode Flotte (C) ?", reponse: "C'est un mode communautaire. Entrez un ID commun (ex: ASSOCIATION-PECHE) pour voir les autres membres, partager les oiseaux et les prises de poisson." },
  { categorie: "Boat Tracker", ordre: 49, question: "Comment signaler une prise de poisson ?", reponse: "Cliquez sur 'Signaler Prise' et choisissez l'espèce. Une icône colorée s'affiche sur la carte pour tous les membres du groupe Flotte (C)." },
  { categorie: "Boat Tracker", ordre: 50, question: "Suis-je visible par tout le monde en mode Flotte ?", reponse: "Seulement si vous activez l'interrupteur 'Partager avec la flotte'. Sinon, vous recevez les alertes des autres tout en restant invisible." },
  { categorie: "Boat Tracker", ordre: 51, question: "Qui peut effacer l'historique ?", reponse: "Seul l'émetteur peut vider le journal de bord pour tout le monde via le bouton Reset." },
  { categorie: "Boat Tracker", ordre: 52, question: "Peut-on copier un point GPS de l'historique ?", reponse: "Oui, cliquez sur le bouton 'Copier' à côté de chaque événement pour récupérer les coordonnées Latitude/Longitude." },
  { categorie: "Boat Tracker", ordre: 53, question: "Le SMS d'urgence inclut-il le nom du navire ?", reponse: "Oui, votre surnom configuré (ex: [TITANIC]) est ajouté au début du message." },
  { categorie: "Boat Tracker", ordre: 54, question: "Peut-on voir le niveau de batterie de l'autre ?", reponse: "Oui, le niveau et l'état de charge s'affichent à côté du nom du navire sur la carte et dans le journal." },
  { categorie: "Boat Tracker", ordre: 55, question: "L'ID de partage est-il définitif ?", reponse: "Vous pouvez le changer dans les réglages de l'émetteur si besoin." },
  { categorie: "Boat Tracker", ordre: 56, question: "Comment régler le volume des alertes ?", reponse: "Utilisez le curseur de volume dans l'accordéon 'Notifications & Sons'." },
  { categorie: "Boat Tracker", ordre: 57, question: "Pourquoi la précision GPS varie-t-elle (+/- Xm) ?", reponse: "Cela dépend de la qualité de réception de votre smartphone et du nombre de satellites verrouillés." },
  { categorie: "Boat Tracker", ordre: 58, question: "Le Boat Tracker fonctionne-t-il sans réseau ?", reponse: "Le GPS fonctionne, mais la transmission vers les récepteurs nécessite une connexion (3G/4G/Starlink)." },
  { categorie: "Boat Tracker", ordre: 59, question: "Que faire en cas d'erreur de statut automatique ?", reponse: "Utilisez le bouton 'ERREUR / REPRISE MODE NORMAL' pour relancer une analyse de 30 secondes." },
  { categorie: "Boat Tracker", ordre: 60, question: "Puis-je être émetteur et récepteur à la fois ?", reponse: "Non, il faut choisir un mode par appareil." },
  { categorie: "Boat Tracker", ordre: 101, question: "Comment suivre la péremption de mon matériel de sécurité ?", reponse: "Allez dans l'onglet 'Réglementation' > 'Sécurité & Armement'. Ajoutez un navire et ses équipements (fusées, extincteurs)." },
  { categorie: "Boat Tracker", ordre: 102, question: "Où s'affichent les alertes de péremption ?", reponse: "Un bandeau orange d'alerte apparaît automatiquement en haut de la page 'Accueil' 3 mois avant l'échéance." },
  { categorie: "Boat Tracker", ordre: 110, question: "Qu'est-ce que l'Angle de Tir / Sécurité ?", reponse: "C'est une zone de surveillance (cône bleu clair). Si un coéquipier y pénètre, vous recevez une alerte sonore." },
  { categorie: "Boat Tracker", ordre: 111, question: "Comment régler la direction de l'angle ?", reponse: "Utilisez le curseur dans vos réglages : 0° est le centre, réglable de -180° à +180°." },
  { categorie: "Boat Tracker", ordre: 112, question: "Quelle est la portée maximale de l'angle ?", reponse: "Réglable jusqu'à 2000m (2 km). La détection s'adapte automatiquement à cette distance." },

  // --- CHASSE (15) ---
  { categorie: "Chasse", ordre: 61, question: "Comment rejoindre une battue ?", reponse: "Entrez le code session (CH-XXXX) fourni par l'organisateur." },
  { categorie: "Chasse", ordre: 62, question: "Pourquoi signaler 'Gibier en vue' ?", reponse: "Cela envoie une notification push et un son immédiat à tous vos partenaires." },
  { categorie: "Chasse", ordre: 63, question: "La table de tir est-elle balistique ?", reponse: "C'est une simulation théorique basée sur un zérotage à 100m. Réglez toujours votre arme en réel." },
  { categorie: "Chasse", ordre: 64, question: "Comment voir le vent en brousse ?", reponse: "Consultez la carte du vent dans l'onglet Chasse pour anticiper votre approche." },
  { categorie: "Chasse", ordre: 65, question: "Puis-je changer ma couleur sur la carte ?", reponse: "Oui, dans vos préférences de profil ou dans les réglages de la session." },
  { categorie: "Chasse", ordre: 66, question: "Comment fonctionne le simulateur de gerbe ?", reponse: "Il permet de voir le diamètre d'impact des plombs (n°2 à n°9) en fonction du Choke (Lisse à Full) et de la distance choisie." },
  { categorie: "Chasse", ordre: 67, question: "Comment régler ma lunette avec la table de tir ?", reponse: "Indiquez votre distance de zéro (ex: 100m). Le tableau calcule alors les clics (1 clic = 1cm à 100m) à appliquer sur vos tourelles pour compenser la chute à d'autres distances." },
  { categorie: "Chasse", ordre: 68, question: "Le silencieux change-t-ils la trajectoire ?", reponse: "Oui, l'app simule un gain de +2% sur la vitesse initiale ($V_0$) car le silencieux prolonge la poussée des gaz, rendant la trajectoire plus tendue." },
  { categorie: "Chasse", ordre: 69, question: "Peut-on saisir ses propres munitions ?", reponse: "Oui, le modèle 'PERSONNALISÉ' permet de saisir manuellement le poids, la vitesse ($V_0$) et le coefficient balistique ($BC$) pour vos chargements personnels." },
  { categorie: "Chasse", ordre: 70, question: "Pourquoi y a-t-il une alerte éthique sur les plombs ?", reponse: "Le simulateur vous prévient si la gerbe devient trop large (ex: plomb n°6 à 40m), risquant de blesser le gibier au lieu de le prélever proprement." },
  { categorie: "Chasse", ordre: 71, question: "Comment compenser le vent latéral ?", reponse: "Saisissez la vitesse du vent et sa direction (en horloge). Le calculateur vous donne le nombre de clics à appliquer sur votre tourelle de dérive (DROITE/GAUCHE)." },
  { categorie: "Chasse", ordre: 72, question: "Quel plomb choisir pour le Notou ?", reponse: "Le plomb n°6 est la référence pour le Notou et le Pigeon vert. Le n°2 est conseillé pour la Roussette ou les gros canards." },
  { categorie: "Chasse", ordre: 73, question: "Le frein de bouche modifie-t-il les clics ?", reponse: "Non, il n'influe pas sur la trajectoire mais améliore la stabilité du canon pour un second tir plus rapide." },
  { categorie: "Chasse", ordre: 74, question: "Pourquoi limiter les fusils lisses à 100m ?", reponse: "Au-delà de 100m, la chute de vitesse et la dispersion des balles de fusils lisses (Brenneke/Sauvestre) rendent le tir trop imprécis pour la chasse." },
  { categorie: "Chasse", ordre: 75, question: "Qui voit ma position en chasse ?", reponse: "Uniquement les personnes ayant rejoint votre code de session spécifique." },
  { categorie: "Chasse", ordre: 108, question: "Comment utiliser 'Mon Râtelier' ?", reponse: "Allez dans l'onglet Chasse > vignettes 'Balistique'. Enregistrez vos armes avec leur calibre et munition favorite. Dans la Table de Tir, utilisez le menu 'Charger une arme' pour remplir instantanément tous les paramètres techniques." },
  { categorie: "Chasse", ordre: 109, question: "Puis-je enregistrer plusieurs carabines ?", reponse: "Oui, vous pouvez créer un nombre illimité de fiches personnalisées. Chaque fiche mémorise ses réglages propres (Zéro, poids, munition)." },
  { categorie: "Chasse", ordre: 113, question: "La détection de collision est-elle mutuelle ?", reponse: "Oui. Vous recevez une alerte si quelqu'un entre dans votre zone de tir, mais aussi si VOUS entrez dans la zone d'un coéquipier (si son angle est actif)." },
  { categorie: "Chasse", ordre: 114, question: "Où voir la précision du GPS ?", reponse: "La précision s'affiche sous forme de badge (+/- Xm) dans la liste des participants de votre équipe." },

  // --- CHAMPS (15) ---
  { categorie: "Champs", ordre: 76, question: "Pourquoi l'arrosage est en secondes ?", reponse: "Pour vous aider à doser précisément au jet d'eau selon les besoins de chaque plante." },
  { categorie: "Champs", ordre: 77, question: "C'est quoi un jour 'Racines' ?", reponse: "Un jour où l'influence lunaire favorise les carottes, oignons, radis, etc." },
  { categorie: "Champs", ordre: 78, question: "Le scanner diagnostique-t-ils les maladies ?", reponse: "Oui, photographiez une feuille abîmée pour obtenir un conseil de traitement local." },
  { categorie: "Champs", ordre: 79, question: "Comment marche le Bilan Stratégique ?", reponse: "L'IA analyse votre inventaire jardin et la météo live pour créer votre plan d'action du jour." },
  { categorie: "Champs", ordre: 80, question: "Peut-on planter des tomates toute l'année ?", reponse: "Oui, mais elles préfèrent la saison fraîche pour éviter le mildiou excessif." },
  { categorie: "Champs", ordre: 81, question: "Quelle lune pour tailler les arbres ?", reponse: "Lune descendante (sève en bas) pour ne pas épuiser l'arbre." },
  { categorie: "Champs", ordre: 82, question: "Pourquoi l'IA me dit de ne pas arroser ?", reponse: "Elle a détecté une pluie récente ou forte prévue à votre commune via la météo live." },
  { categorie: "Champs", ordre: 83, question: "Comment identifier une graine ?", reponse: "Utilisez le scanner IA dans l'onglet 'Guide Culture'." },
  { categorie: "Champs", ordre: 84, question: "C'est quoi l'engrais vert ?", reponse: "Des plantes (trèfle, phacélie) semées pour enrichir naturellement votre terre." },
  { categorie: "Champs", ordre: 85, question: "L'IA connaît-elle les plantes de NC ?", reponse: "Oui, elle est entraînée sur la flore tropicale et les variétés spécifiques du Caillou." },
  { categorie: "Champs", ordre: 86, question: "Comment ajouter une plante au jardin ?", reponse: "Dans 'Mon Jardin', cliquez sur Ajouter et saisissez le nom ou utilisez le scanner." },
  { categorie: "Champs", ordre: 87, question: "Peut-on suivre les arbres fruitiers ?", reponse: "Oui, l'onglet Jardin permet de gérer arbres, fleurs et potager." },
  { categorie: "Champs", ordre: 88, question: "Comment marche le calendrier lunaire ?", reponse: "Il affiche visuellement les phases et le zodiaque pour chaque jour du mois." },
  { categorie: "Champs", ordre: 89, question: "Quelles sont les variétés de tomates en NC ?", reponse: "Heatmaster et Floradade sont les plus résistantes à notre chaleur." },
  { categorie: "Champs", ordre: 90, question: "L'IA corrige-t-elle les noms de plantes ?", reponse: "Oui, si vous écrivez 'mangue', elle corrigera en 'Manguier' pour un suivi correct." },

  // --- COMPTE (10) ---
  { categorie: "Compte", ordre: 91, question: "Comment activer un jeton cadeau ?", reponse: "Allez dans 'Compte', saisissez le code dans 'Activer un jeton' et validez." },
  { categorie: "Compte", ordre: 92, question: "Puis-je utiliser l'app sur 2 téléphones ?", reponse: "Oui, connectez-vous simplement avec le même email sur les deux appareils." },
  { categorie: "Compte", ordre: 93, question: "Comment résilier mon abonnement ?", reponse: "L'abonnement est géré via votre compte PayPal ou les réglages de votre store." },
  { categorie: "Compte", ordre: 94, question: "J'ai oublié mon mot de passe ?", reponse: "Sur l'écran de connexion, cliquez sur 'Mot de passe oublié' pour recevoir un mail de reset." },
  { categorie: "Compte", ordre: 95, question: "À quoi sert le mode 'Limité' ?", reponse: "À consulter rapidement une info (marée, vent) sans être abonné." },
  { categorie: "Compte", ordre: 96, question: "Comment changer mon email ?", reponse: "Pour des raisons de sécurité, contactez le support via un ticket." },
  { categorie: "Compte", ordre: 97, question: "Les notifications push sont-elles gratuites ?", reponse: "Oui, elles sont incluses pour tous les utilisateurs." },
  { categorie: "Compte", ordre: 98, question: "Comment supprimer mon compte ?", reponse: "Envoyez une demande de suppression via le support technique." },
  { categorie: "Compte", ordre: 99, question: "L'abonnement est-il remboursable ?", reponse: "Consultez nos conditions générales de vente sur le site officiel." },
  { categorie: "Compte", ordre: 100, question: "Comment devenir testeur bêta ?", reponse: "Contactez l'administrateur via la messagerie du support." },
];
