
import { FishSpeciesInfo } from './types';

export const lagoonFishData: FishSpeciesInfo[] = [
  {
    id: 'baleinier',
    name: 'Baleinier',
    scientificName: 'Aprion virescens',
    gratteRisk: 0.2,
    gratteRiskSmall: 0.1,
    gratteRiskMedium: 0.2,
    gratteRiskLarge: 0.5,
    lengthSmall: '< 40cm',
    lengthMedium: '40-70cm',
    lengthLarge: '> 70cm',
    culinaryAdvice: 'Chair ferme et savoureuse. Excellent en grillade, en steaks ou en carpaccio.',
    fishingAdvice: 'Se pêche souvent à la traîne ou au vif. Très combatif, ne pas lâcher de mou.',
    category: 'Large',
    imagePlaceholder: 'fish-baleinier'
  },
  {
    id: 'barracuda',
    name: 'Barracuda, bécune',
    scientificName: 'Sphyraena barracuda',
    gratteRisk: 0.5,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.5,
    gratteRiskLarge: 5.0,
    lengthSmall: '< 60cm',
    lengthMedium: '60-100cm',
    lengthLarge: '> 100cm',
    culinaryAdvice: 'Chair fine mais attention à la gratte sur les gros spécimens (>80cm). Consommer de préférence les petits.',
    fishingAdvice: 'Attaque tout ce qui brille. Leurres de traîne ou poppers. Attention aux dents lors du décrochage.',
    category: 'Large',
    imagePlaceholder: 'fish-barracuda'
  },
  {
    id: 'bec-de-cane-tache-noire',
    name: 'Bec de cane à tache noire',
    scientificName: 'Lethrinus harak',
    gratteRisk: 6.6,
    gratteRiskSmall: 2.5,
    gratteRiskMedium: 6.6,
    gratteRiskLarge: 15.0,
    lengthSmall: '< 20cm',
    lengthMedium: '20-35cm',
    lengthLarge: '> 35cm',
    culinaryAdvice: 'Goût délicat. Parfait en friture ou grillé entier.',
    fishingAdvice: 'Présent dans les herbiers et fonds sableux peu profonds. Ligne fine avec morceaux de bernard-l\'ermite.',
    category: 'Lagon',
    imagePlaceholder: 'fish-bec-de-cane-tache-noire'
  },
  {
    id: 'bec-de-cane-bleute',
    name: 'Bec de cane bleuté',
    scientificName: 'Lethrinus nebulosus',
    gratteRisk: 6.6,
    gratteRiskSmall: 3.0,
    gratteRiskMedium: 6.6,
    gratteRiskLarge: 18.0,
    lengthSmall: '< 30cm',
    lengthMedium: '30-55cm',
    lengthLarge: '> 55cm',
    culinaryAdvice: 'Chair excellente, ferme. Très apprécié en salade tahitienne ou grillé au feu de bois.',
    fishingAdvice: 'Se trouve sur les fonds de sable et débris coralliens. Appâts : calamar, crevette.',
    category: 'Lagon',
    imagePlaceholder: 'fish-bec-de-cane-bleute'
  },
  {
    id: 'bec-de-cane',
    name: 'Bec de cane',
    scientificName: 'Lethrinus nebulosus',
    gratteRisk: 6.6,
    gratteRiskSmall: 3.0,
    gratteRiskMedium: 6.6,
    gratteRiskLarge: 18.0,
    lengthSmall: '< 30cm',
    lengthMedium: '30-55cm',
    lengthLarge: '> 55cm',
    culinaryAdvice: 'Excellent en grillade ou au four. Sa chair est ferme et savoureuse. Très apprécié cru en salade tahitienne.',
    fishingAdvice: 'Se pêche à la ligne au fond ou au poser avec du calamar ou du bernard-l\'ermite. Très combatif.',
    category: 'Lagon',
    imagePlaceholder: 'fish-bec-de-cane'
  },
  {
    id: 'bossu-herbe',
    name: "Bossu d'herbe",
    scientificName: 'Lethrinus variegatus',
    gratteRisk: 6.9,
    gratteRiskSmall: 2.0,
    gratteRiskMedium: 6.9,
    gratteRiskLarge: 12.0,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Petit mais très bon. Souvent frit ou en bouillon.',
    fishingAdvice: 'Pêche de bordure dans les herbiers de faible profondeur.',
    category: 'Lagon',
    imagePlaceholder: 'fish-bossu-herbe'
  },
  {
    id: 'bossu-dore',
    name: 'Bossu doré',
    scientificName: 'Lethrinus chrysostomus',
    gratteRisk: 6.9,
    gratteRiskSmall: 3.0,
    gratteRiskMedium: 6.9,
    gratteRiskLarge: 20.0,
    lengthSmall: '< 25cm',
    lengthMedium: '25-45cm',
    lengthLarge: '> 45cm',
    culinaryAdvice: 'Chair blanche très fine. Idéal au four avec un filet d\'huile d\'olive et des herbes.',
    fishingAdvice: 'Chercher les patates de corail isolées sur les fonds de 5 à 15m. Appât : crevettes ou morceaux de poisson.',
    category: 'Lagon',
    imagePlaceholder: 'fish-bossu-dore'
  },
  {
    id: 'carangue-grosse-tete',
    name: 'Carangue à grosse tête, baoum',
    scientificName: 'Caranx ignobilis',
    gratteRisk: 5.5,
    gratteRiskSmall: 2.0,
    gratteRiskMedium: 5.5,
    gratteRiskLarge: 25.0,
    lengthSmall: '< 50cm',
    lengthMedium: '50-90cm',
    lengthLarge: '> 90cm',
    culinaryAdvice: 'Les gros spécimens sont souvent grattés. Privilégier les poissons de moins de 5kg pour la consommation.',
    fishingAdvice: 'Le graal du pêcheur au popper. Puissance extrême, matériel lourd indispensable.',
    category: 'Recif',
    imagePlaceholder: 'fish-carangue-grosse-tete'
  },
  {
    id: 'carangue-echevelee',
    name: 'Carangue échevelée',
    scientificName: 'Alectis ciliaris',
    gratteRisk: 5.5,
    gratteRiskSmall: 1.0,
    gratteRiskMedium: 5.5,
    gratteRiskLarge: 15.0,
    lengthSmall: '< 30cm',
    lengthMedium: '30-60cm',
    lengthLarge: '> 60cm',
    culinaryAdvice: 'Chair très fine et appréciée. Souvent préparée en filets.',
    fishingAdvice: 'Plus rare, se prend parfois au jig ou au leurre souple.',
    category: 'Lagon',
    imagePlaceholder: 'fish-carangue-echevelee'
  },
  {
    id: 'carangue-noire',
    name: 'Carangue noire',
    scientificName: 'Caranx lugubris',
    gratteRisk: 5.5,
    gratteRiskSmall: 3.0,
    gratteRiskMedium: 5.5,
    gratteRiskLarge: 30.0,
    lengthSmall: '< 40cm',
    lengthMedium: '40-70cm',
    lengthLarge: '> 70cm',
    culinaryAdvice: 'Risque de gratte modéré à élevé. Souvent remise à l\'eau par sécurité.',
    fishingAdvice: 'Zones de courant, passes et récifs extérieurs.',
    category: 'Recif',
    imagePlaceholder: 'fish-carangue-noire'
  },
  {
    id: 'carangue-ombree',
    name: 'Carangue ombrée',
    scientificName: 'Carangoides plagiotaenia',
    gratteRisk: 5.5,
    gratteRiskSmall: 2.0,
    gratteRiskMedium: 5.5,
    gratteRiskLarge: 15.0,
    lengthSmall: '< 25cm',
    lengthMedium: '25-45cm',
    lengthLarge: '> 45cm',
    culinaryAdvice: 'Chair honnête, souvent consommée grillée.',
    fishingAdvice: 'Moins puissante que la GT, se prend sur des leurres de taille moyenne.',
    category: 'Lagon',
    imagePlaceholder: 'fish-carangue-ombree'
  },
  {
    id: 'gaterin',
    name: 'Gaterin à bandes diagonale',
    scientificName: 'Plectorhinchus lineatus',
    gratteRisk: 0.8,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.8,
    gratteRiskLarge: 3.0,
    lengthSmall: '< 25cm',
    lengthMedium: '25-45cm',
    lengthLarge: '> 45cm',
    culinaryAdvice: 'Chair comestible mais parfois jugée fade. Préférer une préparation épicée ou en sauce.',
    fishingAdvice: 'Se pêche souvent près du fond, sous les surplombs de corail.',
    category: 'Lagon',
    imagePlaceholder: 'fish-gaterin'
  },
  {
    id: 'jaunet',
    name: 'Jaunet',
    scientificName: 'Lutjanus fulviflamma',
    gratteRisk: 0.8,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.8,
    gratteRiskLarge: 2.5,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Petit vivanneau délicieux frit ou grillé entier.',
    fishingAdvice: 'Abondant autour des patates de corail. Facile à prendre à la ligne légère.',
    category: 'Lagon',
    imagePlaceholder: 'fish-jaunet'
  },
  {
    id: 'lanterne',
    name: 'Lanterne Gros oeil',
    scientificName: 'Priacanthus hamrur',
    gratteRisk: 0.2,
    gratteRiskSmall: 0.1,
    gratteRiskMedium: 0.2,
    gratteRiskLarge: 0.5,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Peu de chair mais excellente. Attention, la peau est très dure, comme du papier de verre.',
    fishingAdvice: 'Pêche de nuit principalement. Vit dans les anfractuosités du corail.',
    category: 'Lagon',
    imagePlaceholder: 'fish-lanterne'
  },
  {
    id: 'loche-castex-levres',
    name: 'Loche castex grosses lèvres',
    scientificName: 'Plectorhinchus chaetodonoides',
    gratteRisk: 0.8,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.8,
    gratteRiskLarge: 4.0,
    lengthSmall: '< 30cm',
    lengthMedium: '30-55cm',
    lengthLarge: '> 55cm',
    culinaryAdvice: 'Semblable au Gaterin. Chair blanche correcte.',
    fishingAdvice: 'Souvent rencontrée en apnée, moins fréquente à la ligne.',
    category: 'Lagon',
    imagePlaceholder: 'fish-loche-castex-levres'
  },
  {
    id: 'loche-castex',
    name: 'Loche castex',
    scientificName: 'Plectropomus laevis',
    gratteRisk: 17.9,
    gratteRiskSmall: 5.0,
    gratteRiskMedium: 17.9,
    gratteRiskLarge: 45.0,
    lengthSmall: '< 40cm',
    lengthMedium: '40-80cm',
    lengthLarge: '> 80cm',
    culinaryAdvice: 'Excellente qualité de chair. Attention aux gros individus souvent porteurs de gratte.',
    fishingAdvice: 'Se poste près des structures. Attaque franche au jig ou au vif.',
    category: 'Lagon',
    imagePlaceholder: 'fish-loche-castex'
  },
  {
    id: 'loche-merou',
    name: 'Loche Mérou',
    scientificName: 'Epinephelus sp.',
    gratteRisk: 17.9,
    gratteRiskSmall: 4.0,
    gratteRiskMedium: 17.9,
    gratteRiskLarge: 40.0,
    lengthSmall: '< 30cm',
    lengthMedium: '30-60cm',
    lengthLarge: '> 60cm',
    culinaryAdvice: 'Chair dense et gélatineuse, parfaite pour les bouillons ou le four.',
    fishingAdvice: 'Pêche au fond au poser. Chercher les trous dans le récif.',
    category: 'Lagon',
    imagePlaceholder: 'fish-loche-merou'
  },
  {
    id: 'loche-truite',
    name: 'Loche truite',
    scientificName: 'Plectropomus leopardus',
    gratteRisk: 0.2,
    gratteRiskSmall: 0.1,
    gratteRiskMedium: 0.2,
    gratteRiskLarge: 1.5,
    lengthSmall: '< 35cm',
    lengthMedium: '35-55cm',
    lengthLarge: '> 55cm',
    culinaryAdvice: 'Un des meilleurs poissons du Caillou. Chair floconneuse. Parfait à la vapeur ou à la crème.',
    fishingAdvice: 'Se pêche au leurre souple ou au jig près du récif. Attention, elle cherche tout de suite à s\'enraguer.',
    category: 'Lagon',
    imagePlaceholder: 'fish-loche-truite'
  },
  {
    id: 'perroquet-bandes-bleues',
    name: 'Perroquet à bandes bleues',
    scientificName: 'Scarus ghobban',
    gratteRisk: 4.0,
    gratteRiskSmall: 1.0,
    gratteRiskMedium: 4.0,
    gratteRiskLarge: 12.0,
    lengthSmall: '< 20cm',
    lengthMedium: '20-40cm',
    lengthLarge: '> 40cm',
    culinaryAdvice: 'Chair très tendre. Délicieux en papillote. Ne pas trop cuire car la chair devient vite molle.',
    fishingAdvice: 'Se prend principalement en chasse sous-marine.',
    category: 'Lagon',
    imagePlaceholder: 'fish-perroquet-bandes-bleues'
  },
  {
    id: 'picot-canaque',
    name: 'Picot canaque',
    scientificName: 'Siganus argenteus',
    gratteRisk: 0.7,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.7,
    gratteRiskLarge: 2.0,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Le préféré de beaucoup. Chair fine, idéal grillé avec un peu de citron.',
    fishingAdvice: 'Pêche au filet ou à la ligne fine sur les tombants.',
    category: 'Lagon',
    imagePlaceholder: 'fish-picot-canaque'
  },
  {
    id: 'picot-chirurgien',
    name: 'Picot chirurgien',
    scientificName: 'Acanthurus sp.',
    gratteRisk: 0.7,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.7,
    gratteRiskLarge: 3.0,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Peu épaisse, chair appréciée mais attention aux "scalpels" sur la queue lors du nettoyage.',
    fishingAdvice: 'Principalement chasse sous-marine sur le platier.',
    category: 'Lagon',
    imagePlaceholder: 'fish-picot-chirurgien'
  },
  {
    id: 'picot-gris',
    name: 'Picot gris',
    scientificName: 'Siganus sp.',
    gratteRisk: 0.7,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.7,
    gratteRiskLarge: 2.0,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Très commun, chair simple et bonne. Toujours bon en grillade.',
    fishingAdvice: 'Ligne fine avec de la pâte ou de la mie de pain.',
    category: 'Lagon',
    imagePlaceholder: 'fish-picot-gris'
  },
  {
    id: 'picot-nid-abeille',
    name: "Picot nid d'abeille",
    scientificName: 'Siganus stellatus',
    gratteRisk: 0.7,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.7,
    gratteRiskLarge: 2.0,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Identique aux autres picots. Chair blanche très saine.',
    fishingAdvice: 'Platier et zones coralliennes.',
    category: 'Lagon',
    imagePlaceholder: 'fish-picot-nid-abeille'
  },
  {
    id: 'picot-raye',
    name: 'Picot rayé',
    scientificName: 'Siganus lineatus',
    gratteRisk: 0.7,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.7,
    gratteRiskLarge: 2.0,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Indétrônable en grillade. On le mange entier après l\'avoir écaillé soigneusement.',
    fishingAdvice: 'Se pêche souvent au filet ou à la ligne fine avec de la pâte. Attention aux épines venimeuses !',
    category: 'Lagon',
    imagePlaceholder: 'fish-picot-raye'
  },
  {
    id: 'poisson-perroquet',
    name: 'Poisson-perroquet',
    scientificName: 'Scaridae sp.',
    gratteRisk: 4.0,
    gratteRiskSmall: 1.0,
    gratteRiskMedium: 4.0,
    gratteRiskLarge: 15.0,
    lengthSmall: '< 20cm',
    lengthMedium: '20-40cm',
    lengthLarge: '> 40cm',
    culinaryAdvice: 'Chair délicate. Se cuisine souvent entier ou en papillote.',
    fishingAdvice: 'Chasse sous-marine ou par hasard à la ligne.',
    category: 'Lagon',
    imagePlaceholder: 'fish-poisson-perroquet'
  },
  {
    id: 'rouget-nuit',
    name: 'Rouget de nuit',
    scientificName: 'Parupeneus sp.',
    gratteRisk: 4.9,
    gratteRiskSmall: 1.5,
    gratteRiskMedium: 4.9,
    gratteRiskLarge: 10.0,
    lengthSmall: '< 15cm',
    lengthMedium: '15-25cm',
    lengthLarge: '> 25cm',
    culinaryAdvice: 'Chair fine au goût de crevette. Délicieux simplement poêlé.',
    fishingAdvice: 'Pêche nocturne sur le sable.',
    category: 'Lagon',
    imagePlaceholder: 'fish-rouget-nuit'
  },
  {
    id: 'saumonee-loche-bleu',
    name: 'Saumonée loche bleu',
    scientificName: 'Plectropomus sp.',
    gratteRisk: 14.8,
    gratteRiskSmall: 4.0,
    gratteRiskMedium: 14.8,
    gratteRiskLarge: 35.0,
    lengthSmall: '< 35cm',
    lengthMedium: '35-60cm',
    lengthLarge: '> 60cm',
    culinaryAdvice: 'Exceptionnel. La chair est fondante.',
    fishingAdvice: 'Leurres souples en profondeur modérée.',
    category: 'Lagon',
    imagePlaceholder: 'fish-saumonee-loche-bleu'
  },
  {
    id: 'saumonee',
    name: 'Saumonée',
    scientificName: 'Plectropomus leopardus',
    gratteRisk: 14.8,
    gratteRiskSmall: 4.0,
    gratteRiskMedium: 14.8,
    gratteRiskLarge: 35.0,
    lengthSmall: '< 35cm',
    lengthMedium: '35-60cm',
    lengthLarge: '> 60cm',
    culinaryAdvice: 'Le must du lagon. Se déguste à toutes les sauces.',
    fishingAdvice: 'Passes et zones de récif actif.',
    category: 'Recif',
    imagePlaceholder: 'fish-saumonee'
  },
  {
    id: 'tazard',
    name: 'Tazard',
    scientificName: 'Scomberomorus commerson',
    gratteRisk: 6.4,
    gratteRiskSmall: 2.0,
    gratteRiskMedium: 6.4,
    gratteRiskLarge: 18.0,
    lengthSmall: '< 60cm',
    lengthMedium: '60-100cm',
    lengthLarge: '> 100cm',
    culinaryAdvice: 'Le roi du sashimi en Calédonie. Se mange aussi très bien en steaks grillés ou fumé.',
    fishingAdvice: 'Se pêche à la traîne rapide (7-9 nds) avec des leurres à bavette longue (Rapala Magnum).',
    category: 'Large',
    imagePlaceholder: 'fish-tazard'
  },
  {
    id: 'vieille-corail',
    name: 'Vieille de corail',
    scientificName: 'Cephalopholis argus',
    gratteRisk: 0.2,
    gratteRiskSmall: 0.1,
    gratteRiskMedium: 0.2,
    gratteRiskLarge: 2.0,
    lengthSmall: '< 20cm',
    lengthMedium: '20-35cm',
    lengthLarge: '> 35cm',
    culinaryAdvice: 'Méfiance vis-à-vis de la gratte. Chair fine mais goût parfois fort.',
    fishingAdvice: 'Vit dans le corail peu profond. Très facile à prendre.',
    category: 'Lagon',
    imagePlaceholder: 'fish-vieille-corail'
  },
  {
    id: 'vivanneau-tetu',
    name: 'Vivanneau têtu',
    scientificName: 'Lutjanus malabaricus',
    gratteRisk: 0.2,
    gratteRiskSmall: 0.1,
    gratteRiskMedium: 0.2,
    gratteRiskLarge: 1.0,
    lengthSmall: '< 30cm',
    lengthMedium: '30-60cm',
    lengthLarge: '> 60cm',
    culinaryAdvice: 'Chair excellente. Très bon au four ou en court-bouillon.',
    fishingAdvice: 'Se pêche en profondeur sur les tombants.',
    category: 'Large',
    imagePlaceholder: 'fish-vivanneau-tetu'
  },
  {
    id: 'wahoo',
    name: 'Wahoo',
    scientificName: 'Acanthocybium solandri',
    gratteRisk: 0.8,
    gratteRiskSmall: 0.2,
    gratteRiskMedium: 0.8,
    gratteRiskLarge: 2.0,
    lengthSmall: '< 80cm',
    lengthMedium: '80-120cm',
    lengthLarge: '> 120cm',
    culinaryAdvice: 'Chair exceptionnelle, très proche du thon mais plus fine. Parfait en steaks.',
    fishingAdvice: 'Pêche de hauturier à la traîne rapide.',
    category: 'Large',
    imagePlaceholder: 'fish-wahoo'
  }
];
